name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Angular Deploy gh-pages Actions
        uses: AhsanAyaz/angular-deploy-gh-pages-actions@v1.4.0
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
          angular_project_dir: ./
          build_configuration: production
          base_href: /
          deploy_branch: main
          angular_dist_build_folder: dist/portifolio
          run_lint: false
          skip_failure: false
